### ISSUE TITLE
Week4 Exercises (a few confusions)

### ISSUE THREAD

**Issue by sarahashjones** [sflippl/r-lectures#1]
Hi there, 
I went back through the class and lecture tonight and have a few of the exercises that I am still stuck on and/or unsure. 
I was wondering if you could help a little? I promise it isn't as long as it looks, I've included the questions and the attempted answers I got - a few of them I just am not sure if I'm missing something!

#############################################################

1. Exercise 1.2 Turn the character (college) column into a factor. 
I don't think I fully understand the difference between a column and a factor...
fct <- factor(x, levels = colleges) 
I'm assuming it links to this piece here but I am not certain I understand the purpose of that line. 

####################################################################

2. Exercise 2.3 I think I might be missing something fundamental here...
#What does the one_of() function do? 
?one_of
- selects a variable from a vector selection and places it first in the tibble?

#Why might it be helpful in conjunction with this vector?
  vars <- c("year", "month", "day", "dep_delay", "arr_delay")

flights%>%
  select(month, one_of(vars))
-can pull the most important variable to the front of the tibble from its location in the array? 

##########################################################################
3. Exercise 4 - the section on missing variables - I think I using the wrong command despite pulling from the help section...

#How many flights have a missing dep_time? 
?missing
flights %>%
  filter(dep_time == NA)
#none ? This is not right and I have tried a few variations, I am missing something...

#What other variables are missing? What might these rows represent?
flights %>%
  filter(dep_time == typeof(NA))
  
#Why is NA ^ 0 not missing? 
flights %>%
  filter(dep_time == NA ^ 0)
  - because that is midnight itself? what is the ^ doing??

#Why is NA | TRUE not missing? 
  flights %>%
  filter(dep_time == NA | TRUE)  
- because that includes all the variables? 
  
#Why is FALSE & NA not missing? 
  flights %>%
  filter(dep_time == FALSE & NA)
- because it overfilters?? 
  
Can you figure out the general rule? (NA * 0 is a tricky counterexample!)
NOPE 

####################################################################
Thanks for any clarification you can provide, I got throught all the other exercise okay but just got caught up on these points! Even if you can point me in the direction of the best place to source some clarificaiton I'd be very grateful! :)

Looking forward to next week!

Warmly, 

Sarah

**Comment by sflippl** [comment]
Dear Sarah, 

Apologies for only getting back to you now.

1. That was actually a typo, apologies, "character" is supposed to say "college". Your code is correct and I wanted you to define the column `college` in the tibble in that way, i. e. as a factor.

2. I think that's probably it. These exercises are mostly just supposed to make you think about these functions and their purpose.

3. I'm going to answer your questions in a more general manner by talking about `NA` values. If you still find yourself lost with individual questions afterwards, please let me know and I'll clarify. `NA` is supposed to represent a missing structure, i. e. there is a certain value but this value is not known. This means that if the outcome of a certain operation is the same for every possible value which you could replace `NA` with, you can assume this operation to have the appropriate outcome.

    - Suppose, for instance, that you are comparing `NA` with `NA`. These variables represent distinct values and they could therefore be replaced either by the same or different values. Therefore, you do not know if `NA==NA`, i. e. the value of this operation is, again, unknown.
    - If you consider `NA^0`, the outcome is 1 for every possible value. Thus, you get 1 as an outcome. (`NA*0` is a counterexample which points out that generally, this does not work for all constant functions.)
    - The same applies for operations with logical values.

Let me know if you have any other questions. I will get back to you sooner this time, I promise. :)
